# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='gender',
            field=models.CharField(choices=[('stallion', 'Stallion'), ('mare', 'Mare'), ('gelding', 'Gelding')], default='stallion', max_length=25),
        ),
        migrations.AddField(
            model_name='horse',
            name='height',
            field=models.IntegerField(default=12),
        ),
    ]
