# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_auto_20171027_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='expression',
            field=models.IntegerField(choices=[(0, 'Recessive'), (1, 'Dominant')]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='stat_type',
            field=models.IntegerField(choices=[(0, 'Fixed'), (1, 'Flexible')]),
        ),
    ]
