# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0009_auto_20171027_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='expression',
            field=models.IntegerField(choices=[(0, 'Recessive'), (1, 'Dominant')]),
        ),
        migrations.AlterField(
            model_name='horsegene',
            name='genotype',
            field=models.CharField(max_length=2),
        ),
    ]
