# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0010_auto_20171027_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.FloatField(max_length=3)),
                ('temperament', models.FloatField(max_length=3)),
                ('movement', models.FloatField(max_length=3)),
                ('speed', models.FloatField(max_length=3)),
                ('strength', models.FloatField(max_length=3)),
                ('intelligence', models.FloatField(max_length=3)),
                ('agility', models.FloatField(max_length=3)),
                ('trainability', models.FloatField(max_length=3)),
                ('personality', models.FloatField(max_length=3)),
                ('health', models.FloatField(max_length=3)),
                ('fitness', models.FloatField(max_length=3)),
                ('stamina', models.FloatField(max_length=3)),
                ('showing', models.FloatField(max_length=3)),
                ('breeding', models.FloatField(max_length=3)),
                ('heritability', models.FloatField(max_length=3)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses.Horse')),
            ],
        ),
    ]
