# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0011_horsestat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horsestat',
            old_name='agility',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='breeding',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='fitness',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='health',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='heritability',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='showing',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='stamina',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='temperament',
        ),
        migrations.RemoveField(
            model_name='horsestat',
            name='trainability',
        ),
        migrations.AddField(
            model_name='horse',
            name='stats',
            field=models.ManyToManyField(related_name='stats', through='horses.HorseStat', to='horses.Stat'),
        ),
        migrations.AddField(
            model_name='horsestat',
            name='stat',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='horse_stat', to='horses.Stat'),
        ),
        migrations.AlterField(
            model_name='horsestat',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_stat', to='horses.Horse'),
        ),
    ]
