# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0012_auto_20171027_2007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horsestat',
            unique_together=set([('horse', 'stat')]),
        ),
    ]
