# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0013_auto_20171027_2029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horsegene',
            unique_together=set([('horse', 'gene')]),
        ),
    ]
