# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0015_auto_20171029_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='genes',
            field=models.ManyToManyField(to='horses.Gene'),
        ),
    ]
