# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0019_auto_20171030_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='gene_type',
            field=models.CharField(choices=[(0, 'Base'), (1, 'Dilution'), (2, 'Modifier'), (3, 'Pattern')], default=0, max_length=30),
        ),
    ]
