# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0021_gene_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_type',
            field=models.CharField(choices=[('base', 'Base'), ('dilution', 'Dilution'), ('modifier', 'Modifier'), ('pattern', 'Pattern')], default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='horse',
            name='color',
            field=models.CharField(max_length=225),
        ),
    ]
