# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horses', '0019_auto_20171030_2232'),
        ('showing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(max_length=50)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showing.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses.Horse')),
                ('type_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TrainingAction')),
            ],
        ),
    ]
