# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horses', '0019_auto_20171030_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=225, unique=True)),
                ('date', models.DateField()),
                ('run', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showing.ClassName')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showing.Show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placing', models.IntegerField(default=0)),
                ('enrty_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showing.ShowClass')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showing.Show')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses.Horse')),
            ],
        ),
        migrations.AddField(
            model_name='classname',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showing.Discipline'),
        ),
    ]
